In [1]:
import numpy as np 

# PIAIC127757 Syed Israr Hussain
# AI_Q2_assignment1_session2

#method 1

a = np.zeros((5,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# method 2

print (np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# method 3

np.empty((5,6)) 

array([[2.48303402e-316, 2.21398326e-316, 0.00000000e+000,
        0.00000000e+000, 6.92555766e-310, 4.82337433e+228],
       [6.14415221e-144, 1.16097020e-028, 6.37112413e-067,
        6.37075937e-062, 1.20053642e-071, 3.97062373e+246],
       [1.16318408e-028, 4.42891760e+175, 8.39567764e+165,
        3.50985387e-033, 1.70323220e-051, 5.04621361e+180],
       [8.37170571e-144, 8.07993712e-144, 1.12855837e+277,
        6.32672840e+180, 2.66371964e+233, 2.16385138e+190],
       [3.58801215e+175, 3.57336834e-062, 2.95833932e-032,
        6.76155305e+170, 2.84453077e+151, 6.92566139e-310]])

In [13]:
# method 4

l = [1,2,3,4,5]
print (type (l))
a = np.array(l)
print (type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# method 5

a = np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [6]:
import numpy as np
# method/ property 6 

a = np.empty((5,4))
print (a)
a.shape


[[1.12094879e-316 1.12152427e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


(5, 4)

In [5]:
# method 7

b =  a.reshape(2,5,2)
b

array([[[1.12094879e-316, 1.12152427e-316],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [7]:
# method/ property 8

b.ndim

3

In [21]:
# method 9

c=np.ones((2,3),dtype=np.float16)
c

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [22]:
# method 10 

a = np.array([[1, 5, 3, 2], [5, 6, 9, 7]])
np.sort(a)

array([[1, 2, 3, 5],
       [5, 6, 7, 9]])

In [3]:
import numpy as np

# method 11

a = np.array(["a","b"])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))
np.concatenate((a,b,))

array(['a', 'b', '5', '6', '7', '8'], dtype='<U21')

In [17]:
# method 12

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7,8]])
# x.size
# y.size
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
# method/ attribute 13

a = np.array([1, 2, 3, 4, 5, 6])
print (a.shape)
a2 = a[np.newaxis,:]
print(a2.shape)
print(a)
print(a2)
print(a2.ndim)

(6,)
(1, 6)
[1 2 3 4 5 6]
[[1 2 3 4 5 6]]
2


In [47]:
# method 15


rng = np.random.default_rng(0)
rng.integers(6, size=(2, 4))

array([[5, 3, 3, 1],
       [1, 0, 0, 0]])

In [48]:
# method 16

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
# method 17

a = np.array([[0, 1, 2], [3, 4, 5]])
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [50]:
# method 18
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [55]:
# method 19

x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
import numpy as np
# method 20

x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a = x.ravel()

a[4]=99
print(x)
print(a)

[[ 1  2  3  4]
 [99  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4 99  6  7  8  9 10 11 12]


In [9]:
# method 21
a = np.array([1, 2, 3, 4, 5, 6])
np.save('testfile',a)


In [10]:
# method 22
b = np.load('testfile.npy')
b

array([1, 2, 3, 4, 5, 6])

In [15]:
# method 23
np.random.seed(5)
x = np.random.randint(9, size=(3, 3))
x


array([[3, 6, 6],
       [0, 8, 4],
       [7, 0, 0]])

In [19]:
# method 24
print(x.item(2,0))
print(x.item(2,1))
print (x.item(2,2))

7
0
0


In [26]:
# method 25
a = np.array([[1, 2], [3, 4]])
print(a)
print(type(a))
b=a.tolist()
print(type(b))


[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'list'>


In [28]:
# method 26

np.random.seed(123)
x = np.random.randint(9, size=(3, 3))
x


array([[2, 2, 6],
       [1, 3, 6],
       [1, 0, 1]])

In [31]:
x.itemset(4, 0)
print(x)
x.itemset((2, 2), 9)
print(x)


[[2 2 6]
 [1 0 6]
 [1 0 9]]
[[2 2 6]
 [1 0 6]
 [1 0 9]]


In [33]:
# method 27
x = np.array([[1,2,3],[4,5,6]], order='F')
x


array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
y = x.copy()
x.fill(0)
print (x)
print (y)

[[0 0 0]
 [0 0 0]]
[[1 2 3]
 [4 5 6]]


In [36]:
# method 28
x.fill(1)
x

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
# method 29
a = np.array([[0, 1], [2, 3]], order='C')
a.resize((2, 1))
a


array([[0],
       [1]])

In [38]:
# method 30

x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [34]:
x = np.array([[[0,1]], [[1,2]], [[3,4]]])
print (x)
print (x.shape)
print (x.size)

x=np.squeeze(x)
print (x)
print (x.shape)
print (x.size)


[[[0 1]]

 [[1 2]]

 [[3 4]]]
(3, 1, 2)
6
[[0 1]
 [1 2]
 [3 4]]
(3, 2)
6


In [33]:
arr = np.array([2, 4, 6, 8, 10], ndmin=6) 
  
# printing array 
print(arr) 
print (arr.shape)
arr=arr.squeeze()
print (arr)
print (arr.shape)

[[[[[[ 2  4  6  8 10]]]]]]
(1, 1, 1, 1, 1, 5)
[ 2  4  6  8 10]
(5,)


In [8]:
# method 31
a = [4, 3, 5, 7, 6, 8]

indices = [0, 1, 2]

np.take(a, indices)

list

In [43]:
# method 32
a = np.arange(5)
print (a)
np.put(a, [0, 2,3], [-44, -55],mode='clip')
a


[0 1 2 3 4]


array([-44,   1, -55, -44,   4])

In [52]:
np.put(a, [0,2], [-44, -55, -65])
a


array([-44,   1, -55, -65,   4])

In [58]:
# method 33

a=np.repeat(3, 4)
print(a)

x = np.array([[1,2],[3,4]])
print (np.repeat(x, 2))


print("repeat axis 1", np.repeat(x, 2, axis=1))
print("repeat axis 0", np.repeat(x, 2, axis=0))
print("repeat axis 0 array", np.repeat(x, [1, 2], axis=0))


[3 3 3 3]
[1 1 2 2 3 3 4 4]
repeat axis 1 [[1 1 2 2]
 [3 3 4 4]]
repeat axis 0 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
repeat axis 0 array [[1 2]
 [3 4]
 [3 4]]


In [75]:
# method 34
choices = [[0, 1, 2, 3], [10, 11, 12, 13],
  [20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

In [76]:

np.choose([2, 4, 1, 0], choices, mode='clip') # 4 goes to 3 (4-1)

array([20, 31, 12,  3])

In [79]:
np.choose([9, 4, 1, 0], choices, mode='wrap') 

array([10,  1, 12,  3])

In [2]:
import numpy as np
# method 35
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [6]:
x = np.array([[0, 3], [2, 2]])
print(x)

ind = np.argsort(x, axis=0)  # sorts along first axis (down)
print (ind)

print (np.take_along_axis(x, ind, axis=0)) # same as np.sort(x, axis=0)


[[0 3]
 [2 2]]
[[0 1]
 [1 0]]
[[0 2]
 [2 3]]


In [10]:
# method 36
a = np.array([3, 4, 2, 1])
a.partition(3)
a


array([2, 1, 3, 4])

In [8]:
a.partition((1, 3))
a


array([1, 2, 3, 4])

In [18]:
# method 37
x = np.array([3, 4, 2, 1])
x[np.argpartition(x, 3)]
print (x)
x1=x[np.argpartition(x, (1, 3))]
print (x1)
y=np.array(x1)


y2=np.take(x,y,mode='clip')
print (y2)

[3 4 2 1]
[1 2 3 4]
[4 2 1 1]


In [3]:
x = [3, 4, 2, 1]
np.array(x)[np.argpartition(x, 3)]


array([2, 1, 3, 4])

In [23]:
# method 38
np.searchsorted([1,3,5,7,9], 2)

1

In [25]:
np.searchsorted([2,5,6,7,9,10], 4, side='right')


1

In [27]:
# method 39
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x
print(x)
np.nonzero(x)


[[3 0 0]
 [0 4 0]
 [5 6 0]]


(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [42]:
# method 40
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
np.compress([1, 0], a, axis=1)

[[1 2]
 [3 4]
 [5 6]]


array([[1],
       [3],
       [5]])

In [47]:
# method 41
a = np.arange(1,5).reshape(2,2)
print (a)

print (a.diagonal())

print (a.diagonal(1))


[[1 2]
 [3 4]]
[1 4]
[2]


In [50]:
# method 42
a = np.arange(9).reshape(3, 3)
print(a)

np.fliplr(a).diagonal()  # Horizontal flip


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 4, 6])

In [51]:
np.flipud(a).diagonal()  # Vertical flip

array([6, 4, 2])

In [53]:
# method 43
a = np.arange(4).reshape((2,2))
print(a)
np.amax(a)   



[[0 1]
 [2 3]]


array([2, 3])

In [55]:
 np.amax(a, axis=0)   # Maxima along the first axis       

array([2, 3])

In [56]:
np.amax(a, axis=1)   # Maxima along the second axis

array([1, 3])

In [57]:
# method 44

a = np.arange(4).reshape((2,2))
print(a)
np.amin(a)           # Minimum of the flattened array

[[0 1]
 [2 3]]


0

In [59]:
np.amin(a, axis=0)   # Minima along the first axis


array([0, 1])

In [58]:
np.amin(a, axis=1)   # Minima along the second axis


array([0, 2])

In [67]:
# method 45
x = np.array([[4, 9, 19, 10],
              [7, 19, 7, 12]])
x

array([[ 4,  9, 19, 10],
       [ 7, 19,  7, 12]])

In [68]:
np.ptp(x, axis=1)


array([15, 12])

In [69]:
np.ptp(x, axis=0)

array([ 3, 10, 12,  2])

In [71]:
# method 46
a = np.arange(10)
print (a)
np.clip(a, 1, 5)

[0 1 2 3 4 5 6 7 8 9]


array([1, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [72]:
# method 47

np.around([0.37, 1.64])

array([0., 2.])

In [73]:
np.around([0.37, 1.64], decimals=1)

array([0.4, 1.6])

In [76]:
np.around([.5, 1.5, 2.5, 3.5, 4.3, 5.7]) # rounds to nearest even value

array([0., 2., 2., 4., 4., 6.])

In [78]:
np.around([1.1,2,3,11], decimals=1) 

array([ 1.1,  2. ,  3. , 11. ])

In [81]:
# method 48

a = np.array([[5, 10], [5, 10]])

np.mean(a)

7.5

In [82]:
# method 49

a = np.array([[5, 10], [5, 10]])

np.std(a)

2.5

In [83]:
# method 50

x = np.array([2, 2, 2, 2])

np.prod(x)

16

In [84]:
np.prod([[1.,2.],[3.,4.]], axis=0)

array([3., 8.])

In [85]:
np.prod([[1.,2.],[3.,4.]], axis=1)

array([ 2., 12.])